In [1]:
import numpy as np 

1. Element-wise Arithmetic

In [4]:
a = np.array([1,9,4])
b = np.array([15,35,96])

print(a + b)
print(a-b)
print(a*b)
print(a/b)


[ 16  44 100]
[-14 -26 -92]
[ 15 315 384]
[0.06666667 0.25714286 0.04166667]


2. Array with Scalars

In [5]:
print(a + 10)
print(b * 2 )

[11 19 14]
[ 30  70 192]


3.Comparison Operators (Boolean Arrays)

In [7]:
print(a > 5)   
print(b == 2) 

[False  True False]
[False False False]


4. Aggregate Functions (Statistics)

In [8]:
matrix = np.array([ [1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(matrix.sum())      
print(matrix.mean())    
print(matrix.std())      
print(matrix.min())      
print(matrix.max())      


45
5.0
2.581988897471611
1
9


5. Axis-Wise Operations

######  Axis = 0 for  column-wise
######  Axis = 1 for  row-wise

In [9]:
print(matrix.sum(axis=0))     # [12 15 18] → column-wise sum
print(matrix.sum(axis=1))     # [6 15 24] → row-wise sum


[12 15 18]
[ 6 15 24]


 6. Broadcasting - Broadcasting lets you perform operations between arrays of different shapes

In [10]:
a = np.array([1, 2, 3])
b = 10

print(a + b)   


[11 12 13]


In [11]:
m = np.array([[1, 2, 3],[4, 5, 6]])

print(m + 10) 


[[11 12 13]
 [14 15 16]]


In [12]:
col = np.array([[1], [2]])
print(m + col)


[[2 3 4]
 [6 7 8]]
