## WHAT IS NUMPY ??

In [1]:
NumPy is a library for numerical computing in Python. It provides a powerful N-dimensional array object and useful functions for performing mathematical operations efficiently.


SyntaxError: invalid syntax (2246341586.py, line 1)

## IMPORTING THE LIBERARY


In [3]:
import numpy as np 

## Creating 1D , 2D and 3D Array

In [4]:
a = np.array([1,2,3])
print(" 1d array ",a)



#2d array
b = np.array([[1,2],[3,4]])

print("2d array",b)


#3d array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3d array",c)

 1d array  [1 2 3]
2d array [[1 2]
 [3 4]]
3d array [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## zeros_array

In [6]:
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [9]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


## identity_matrix

In [10]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## ARRAY PROPERTIES 

In [5]:
print("shape of a:",a.shape)
print("shape of b:",b.shape)
print("data type of a:",a.dtype)
print("dimension of a:",a.ndim)
print("size of a:",a.size)

shape of a: (3,)
shape of b: (2, 2)
data type of a: int64
dimension of a: 1
size of a: 3


## INDEXING AND SLICING 

In [6]:
print("element at b[0,1]:",b[0,1])
print("secomd column of b:",b[:,1])
print("first row of b:",b[0,:])

element at b[0,1]: 2
secomd column of b: [2 4]
first row of b: [1 2]
