In [1]:
import numpy as np


## Indexing in Numpy

1 D Array Indexing 

In [3]:
arr1  = np.array([10,20,30,40,50])
print(arr1[0]) # it will access first element 
print(arr1[-1]) #  it will access last element 
print(arr1[-3]) # it will access last 3rd element and so on .


10
50
30


2D Array Indexing

In [4]:
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(arr2[0, 0])  
print(arr2[2, 1])


1
8


## Slicing in NumPy

1D Array Slicing

In [7]:
print(arr1[1:4])    
print(arr1[:3])   
print(arr1[-3:])  


[20 30 40]
[10 20 30]
[30 40 50]


2D Array Slicing

In [11]:
#  2x2 subarray
print(arr2[0:2, 1:3])


[[2 3]
 [5 6]]


## Reshaping Arrays

In [12]:
arr = np.arange(1, 13)       
reshaped = arr.reshape(3, 4)  
print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Flatten and Ravel

In [14]:
#flatten() – Returns a copy of the array as 1D

In [13]:
flat = reshaped.flatten()
print(flat)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#.ravel() – Returns a view (changes affect original)

In [16]:
flat2 = reshaped.ravel()
print(flat2)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Transpose 

In [17]:
print(reshaped.T)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
