 ## 1. Matrix Multiplication: dot() and @

In [1]:
import numpy as np 

In [3]:
a = np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

print(np.dot(a,b))
print(a @ b )

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## 2. Transpose: T

In [4]:
print(a.T)
print(b.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


##  3. Identity Matrix: np.eye()

In [7]:
Identity = np.eye(3)
print(Identity)

Identity_2 = np.eye(6)
print(Identity_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


##  4. Determinant: np.linalg.det()

In [11]:
Determinant_1 = np.linalg.det(a)
print(Determinant_1)

-2.0000000000000004


##  5. Inverse of a Matrix: np.linalg.inv()

In [12]:
inv_a = np.linalg.inv(a)
print(inv_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


 Verify: A × A⁻¹ = Identity

In [13]:
print(np.dot(a, inv_a))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


##  6. Solving Linear Equations: np.linalg.solve()

In [14]:
A = np.array([[2, 1], [3, 4]])
B = np.array([8, 18])

X = np.linalg.solve(A, B)
print(X)  
# [2. 4.] → x=2, y=4


[2.8 2.4]
