## 1. Integer Array Indexing

In [5]:
import numpy as np 


a = np.array([10,20,30,40,50,60])
index = [0,2,3]

print(a[index])

[10 30 40]


##  2. Boolean Indexing / Masking

In [10]:
niku = np.array([1,2,3,4,5,6])
mask = niku > 3
print(mask)
print(niku[mask])

[False False False  True  True  True]
[4 5 6]


##  3. Using np.where()

In [13]:
a = np.array([1, 2, 3, 4, 5])

# Get index positions
print(np.where(a > 3))  

# Replace: if > 3 → 99, else → original
print(np.where(a > 3, 99, a)) 


(array([3, 4]),)
[ 1  2  3 99 99]


##  4. Multiple Conditions

In [14]:
a = np.array([10, 15, 20, 25, 30])

# Value that is between 15 and < 30
print(a[(a > 15) & (a < 30)])  # [20 25]

# By using the Not operator
print(a[~(a > 20)])  # [10 15 20]


[20 25]
[10 15 20]


## 5. Fancy Indexing (2D Arrays)

In [16]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])


print(a[[0, 1, 2], [1, 0, 1]])  # [2 3 6]


[2 3 6]
