# Practice Questions

### 1) Create an array of numbers 0–50.
### Extract all even numbers using boolean indexing.

In [13]:
import numpy as np 

In [14]:
a = np.arange(0,51)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [15]:
even = a % 2 ==0
print(a[even])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


### 2) Given a 1D array of marks, extract only the values > 75.
### Replace values < 35 with 0 using np.where().

In [16]:
marks = np.array([23, 45, 78, 34, 90, 12, 67, 88])
good_marks = marks > 75 
print(marks[good_marks])


[78 90 88]


In [17]:
print(np.where(marks <35 , 0 ,marks))

[ 0 45 78  0 90  0 67 88]


### 3)  Create a mask to select values between 20 and 80 from a random 1D array of 15 numbers.

In [19]:
a = np.array([51,92,14,71,60,20,82,86,74,74,87,99,23,2,21])
print(a[(a > 20) & (a < 80)])


[51 71 60 74 74 23 21]


4) ###  In a 2D array of shape (4, 4), replace all values > 10 with -1

In [20]:
arr = np.random.randint(0, 21, size=(4, 4))
arr[arr > 10] = -1

print(arr)


[[ 3 -1 -1 -1]
 [ 0  8 -1  6]
 [ 0  1  7 -1]
 [-1  5  6  7]]
