In [1]:
import numpy as np 

 ## 1. Random Number Generation (np.random)

Random integers between 1–100

In [7]:
random = np.random.randint(1,100,size = 5)
print(random)

[85 43 40 75 99]


Random floats between 0–1

In [8]:
random_float = np.random.rand(4)
print(random_float)

[0.3058688  0.45611586 0.41458154 0.44712824]


Random 2D array of ints

In [9]:
random_matrix = np.random.randint(1,10, size = (3,3))
print(random_matrix)


[[9 1 4]
 [4 1 3]
 [7 8 1]]


## 2. Reproducibility with np.random.seed()

In [13]:
np.random.seed(50)
print(np.random.rand(3))

[0.49460165 0.2280831  0.25547392]


## 3. Shuffling Arrays

In [15]:
niku_1 = np.array([12,23,34,45,56])
np.random.shuffle(niku_1)
print(niku_1)

[45 12 23 34 56]


##  4. Sorting Arrays

In [25]:
a = np.array([89,78,67,56,45,34,2,3,4,5,6,7,8,9,0])

print(np.sort(a))

[ 0  2  3  4  5  6  7  8  9 34 45 56 67 78 89]


 FOR 2D array

In [24]:
b = np.array([[5,8,2],[9,3,6]])

print(np.sort(b,axis = 0))
print(np.sort(b,axis = 1))

[[5 3 2]
 [9 8 6]]
[[2 5 8]
 [3 6 9]]


## 5. Set Operations

 Unique Elements

In [23]:
arr = np.array([1, 2, 3, 1, 2, 4])

print(np.unique(arr))  

[1 2 3 4]


 Intersection, Union, Difference

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.intersect1d(a, b))   
print(np.union1d(a, b))       
print(np.setdiff1d(a, b))     


[3 4]
[1 2 3 4 5 6]
[1 2]
